/*
 * letters.inc
 *
 *  Created: 28.02.2022 17:27:57
 *   Author: atlon
 */ 
ok_a:
		RCALL	Dot
		RCALL	Delay_between_elements
		RCALL	Dash
		RCALL	Delay_between_signs
		RET
ok_b:
		RCALL	Dash
		RCALL	Delay_between_elements
		RCALL	Dot
		RCALL	Delay_between_elements
		RCALL	Dot
		RCALL	Delay_between_elements
		RCALL	Dot
		RCALL	Delay_between_signs
		RET
ok_c:
		RCALL	Dash
		RCALL	Delay_between_elements
		RCALL	Dot
		RCALL	Delay_between_elements
		RCALL	Dash
		RCALL	Delay_between_elements
		RCALL	Dot
		RCALL	Delay_between_signs
		RET
ok_d:
		RCALL	Dash
		RCALL	Delay_between_elements
		RCALL	Dot
		RCALL	Delay_between_elements
		RCALL	Dot
		RCALL	Delay_between_signs
		RET
ok_e:
		RCALL	Dot
		RCALL	Delay_between_signs
		RET
ok_f:
		RCALL	Dot
		RCALL	Delay_between_elements
		RCALL	Dot
		RCALL	Delay_between_elements
		RCALL	Dash
		RCALL	Delay_between_elements
		RCALL	Dot
		RCALL	Delay_between_signs
		RET
ok_g:
		RCALL	Dash
		RCALL	Delay_between_elements
		RCALL	Dash
		RCALL	Delay_between_elements
		RCALL	Dot
		RCALL	Delay_between_signs
		RET
ok_h:
		RCALL	Dot
		RCALL	Delay_between_elements
		RCALL	Dot
		RCALL	Delay_between_elements
		RCALL	Dot
		RCALL	Delay_between_elements
		RCALL	Dot
		RCALL	Delay_between_signs
		RET
ok_i:
		RCALL	Dot
		RCALL	Delay_between_elements
		RCALL	Dot
		RCALL	Delay_between_signs
		RET
ok_j:
		RCALL	Dot
		RCALL	Delay_between_elements
		RCALL	Dash
		RCALL	Delay_between_elements
		RCALL	Dash
		RCALL	Delay_between_elements
		RCALL	Dash
		RCALL	Delay_between_signs
		RET
ok_k:
		RCALL	Dash
		RCALL	Delay_between_elements
		RCALL	Dot
		RCALL	Delay_between_elements
		RCALL	Dash
		RCALL	Delay_between_signs
		RET
ok_l:
		RCALL	Dot
		RCALL	Delay_between_elements
		RCALL	Dash
		RCALL	Delay_between_elements
		RCALL	Dot
		RCALL	Delay_between_elements
		RCALL	Dot
		RCALL	Delay_between_signs
		RET
ok_m:
		RCALL	Dash
		RCALL	Delay_between_elements
		RCALL	Dash
		RCALL	Delay_between_signs
		RET
ok_n:
		RCALL	Dash
		RCALL	Delay_between_elements
		RCALL	Dot
		RCALL	Delay_between_signs
		RET
ok_o:
		RCALL	Dash
		RCALL	Delay_between_elements
		RCALL	Dash
		RCALL	Delay_between_elements
		RCALL	Dash
		RCALL	Delay_between_signs
		RET
ok_p:
		RCALL	Dot
		RCALL	Delay_between_elements
		RCALL	Dash
		RCALL	Delay_between_elements
		RCALL	Dash
		RCALL	Delay_between_elements
		RCALL	Dot
		RCALL	Delay_between_signs
		RET
ok_q:	
		RCALL	Dash
		RCALL	Delay_between_elements
		RCALL	Dash
		RCALL	Delay_between_elements
		RCALL	Dot
		RCALL	Delay_between_elements
		RCALL	Dash
		RCALL	Delay_between_signs
		RET
ok_r:
		RCALL	Dot
		RCALL	Delay_between_elements
		RCALL	Dash
		RCALL	Delay_between_elements
		RCALL	Dot
		RCALL	Delay_between_signs
		RET
ok_s:
		RCALL	Dot
		RCALL	Delay_between_elements
		RCALL	Dot
		RCALL	Delay_between_elements
		RCALL	Dot
		RCALL	Delay_between_signs
		RET
ok_t:
		RCALL	Dash
		RCALL	Delay_between_signs
		RET
ok_u:
		RCALL	Dot
		RCALL	Delay_between_elements
		RCALL	Dot
		RCALL	Delay_between_elements
		RCALL	Dash
		RCALL	Delay_between_signs
		RET
ok_v:
		RCALL	Dot
		RCALL	Delay_between_elements
		RCALL	Dot
		RCALL	Delay_between_elements
		RCALL	Dot
		RCALL	Delay_between_elements
		RCALL	Dash
		RCALL	Delay_between_signs
		RET
ok_w:
		RCALL	Dot
		RCALL	Delay_between_elements
		RCALL	Dash
		RCALL	Delay_between_elements
		RCALL	Dash
		RCALL	Delay_between_signs
		RET
ok_x:
		RCALL	Dash
		RCALL	Delay_between_elements
		RCALL	Dot
		RCALL	Delay_between_elements
		RCALL	Dot
		RCALL	Delay_between_elements
		RCALL	Dash
		RCALL	Delay_between_signs
		RET
ok_y:
		RCALL	Dash
		RCALL	Delay_between_elements
		RCALL	Dot
		RCALL	Delay_between_elements
		RCALL	Dash
		RCALL	Delay_between_elements
		RCALL	Dash
		RCALL	Delay_between_signs
		RET
ok_z:
		RCALL	Dash
		RCALL	Delay_between_elements
		RCALL	Dash
		RCALL	Delay_between_elements
		RCALL	Dot
		RCALL	Delay_between_elements
		RCALL	Dot
		RCALL	Delay_between_signs
		RET